language: python

python:
    - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - pip install -r requirements.txt
    - pip install python-coveralls

script:
    - coverage run --source=kirjava -m unittest discover tests

after_success:
  - coveralls
